on:
  push:
    branches: [ master ]
  pull_request:
    types: [ opened, synchronize ]

name: Stats

jobs:
  stats:
    name: Generate Stats
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: cyrilwanner/bundlewatch-comment-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bundlewatch-github-token: ${{ secrets.BUNDLEWATCH_GITHUB_TOKEN }}
